import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/providers";
import { Sarabun, Tajawal } from "next/font/google";

const sarabun = Sarabun({
  subsets: ["latin"],
  variable: "--font-sarabun",
  weight: ["400", "500", "600", "700"],
});
const tajawal = Tajawal({
  subsets: ["latin"],
  variable: "--font-tajawal",
  weight: ["400", "500", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  >
      <body
        className={`${sarabun.className} ${sarabun.variable} ${tajawal.variable} antialiased`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
